decision:

  gaips:
    task: unknown
    noise: 0.05

    cache directory: resources/cache

manager:

  node descriptions:
    - [ porta, entrada ]
    - [ meio da sala, centro da sala, espaço aberto ]
    - [ mesa do ali, baxter, robô, robô vermelho, estação de trabalho ]
    - [ mesa do miguel, bancada dupla, estante, miguel ]
    - [ mesa do joão, bancada individual, mesa redonda, canto da sala, joão ]

  seconds to move: 10

  graph nodes astro points:
    - [-1.05, -4.10]  # Porta
    - [-0.65, -1.95]  # Meio da sala
    - [-1.85, -2.40]  # Baxter
    - [-0.15, -0.10]  # Mesa Miguel
    - [1.50,  -0.05]  # Mesa João

  tts: true

  mic:
    sample rate: 44100
    listening seconds: 5

astro mockup:

  seconds to move: 5